name: Party Event Submission
description: Submit a party event
title: "[Event]: "
labels: ["event-submission"]
body:
  - type: dropdown
    id: event-type
    attributes:
      label: Event Type
      options:
        - Birthday Party
        - BBQ Party
        - Holiday Party
        - Office Party
        - Wedding Reception
    validations:
      required: true
  - type: input
    id: event-name
    attributes:
      label: Event Name
      placeholder: e.g., John's 30th Birthday Bash
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date
      placeholder: YYYY-MM-DD
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Location
      placeholder: e.g., Central Park
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Tell us about your party...
    validations:
      required: true
  - type: input
    id: organizer
    attributes:
      label: Your Name
      placeholder: e.g., John Doe
    validations:
      required: true
